fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.6.0"
  symlinks:
    artifactory: "#{source_dir}"
  repositories:
    docker: git@github.com:garethr/garethr-docker.git
