name 'evenup-artifactory'
version '1.1.0'
author 'Justin Lambert <jlambert@letsevenup.com>'
license 'Apache'
project_page 'https://github.com/evenup/evenup-artifactory'
summary 'Installs the artifactory service'
description 'This module installs the artifactory package, configures and manages the service, and provides a method to fetch artifacts.'
dependency 'evenup/apache', '>= 2.0.0'
dependency 'evenup/backups', '>= 1.1.0'
dependency 'puppetlabs/stdlib'

